apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: quanby-clusterissuer
spec:
  acme:
    email: paul.reinking@quanby.nl
    privateKeySecretRef:
      name: quanby-clusterissuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
        - 'quanby.nl'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: quanby-staging-clusterissuer
spec:
  acme:
    email: paul.reinking@quanby.nl
    privateKeySecretRef:
      name: quanby-staging-clusterissuer
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
        - 'quanby.nl'

