ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hostPath: /
  hostRepo: nexus.k8s-dev-01.quanby.lan
  tls:
    - hosts:
        - nexus.k8s-dev-01.quanby.lan

persistence:
  enabled: true
  storageClass: "px-db"

