apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: asgard
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles:
      - values-quanby.yaml
    path: hello-world
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true