apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: asgard
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      values: |-
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: "/"
          hosts:
          - host: hello-world.{{ .Values.spec.clustername }}
            paths:
            - path: "/test"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
    path: hello-world
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true