apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-kibana
  namespace: argocd
spec:
  destination:
    namespace: kube-elastic-stack
    server: {{ .Values.spec.destination.server }}
  project: hit-asgard
  source:
    chart: kibana
    helm:
      values: |-
        ingress:
          enabled: true
          annotations: 
            kubernetes.io/ingress.class: nginx
          path: /
          hosts:
            - kibana.k8s.lan.quanby.nl
    repoURL: https://helm.elastic.co
    targetRevision: {{ .Values.elastic.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
