apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
spec:
  destination:
    namespace: kube-elastic-stack
    server: {{ .Values.spec.destination.server }}
  project: asgard
  source:
    chart: metricbeat
    repoURL: https://helm.elastic.co
    targetRevision: {{ .Values.elastic.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true