apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  destination:
    namespace: nexus
    server: {{ .Values.spec.destination.server }}
  project: asgard
  source:
    chart: sonatype-nexus
    helm:
      values: |-
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: px-db
    repoURL: https://oteemo.github.io/charts
    targetRevision: 4.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
